/**
 * Copy the ABIs the app needs out of the Foundry build.
 *
 *   node scripts/extract-abi.mjs
 *
 * Generated rather than hand-maintained, and written as `as const` so viem infers argument and
 * return types straight from the contract. A hand-copied ABI drifts silently the moment a
 * signature changes; this way a rename breaks the typecheck instead of the demo.
 */

import {mkdir, readFile, writeFile} from "node:fs/promises";
import {fileURLToPath} from "node:url";
import {dirname, join} from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "..", "contracts", "out");
const target = join(here, "..", "src", "abi");

/** `SafeVault` carries every policy function the UI touches, including the inherited ones. */
const WANTED = [
  ["SafeVault.sol", "SafeVault.json", "safeVaultAbi"],
  ["GuardedAccount.sol", "GuardedAccount.json", "guardedAccountAbi"],
  ["SafeVaultFactory.sol", "SafeVaultFactory.json", "safeVaultFactoryAbi"],
];

await mkdir(target, {recursive: true});

const index = [];
for (const [dir, file, name] of WANTED) {
  const artifact = JSON.parse(await readFile(join(out, dir, file), "utf8"));
  const body =
    `// Generated by scripts/extract-abi.mjs from contracts/out. Do not edit by hand.\n` +
    `export const ${name} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  await writeFile(join(target, `${name}.ts`), body);
  // Extensionless: `moduleResolution: bundler` and Next's webpack both resolve it, while a
  // `.js` specifier makes webpack look for a file that does not exist.
  index.push(`export {${name}} from "./${name}";`);
  console.log(`${name}: ${artifact.abi.length} entries`);
}

await writeFile(
  join(target, "index.ts"),
  `// Generated by scripts/extract-abi.mjs. Do not edit by hand.\n${index.join("\n")}\n`,
);
console.log(`wrote ${target}`);
